# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PruebaTecnicaLoro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PruebaTecnicaLoro

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Firestore'
  pod 'Firebase/Database', :inhibit_warnings => true
end
